// This file is generated by "hygen fsd new"
// Manual changes might be lost - proceed with caution!

import * as TeamModel from './model';

export {
  // FSD:UI:EXPORT
  TeamView
} from './ui';

// FSD:MODEL:EXPORT
export { TeamModel };
