// atomic - autogenerated "organisms" layer

// atomic:re-export:select
// atomic:re-export:select:component

export { default as Select } from './select';

// atomic:re-export:select:types

export type { SelectProps } from './select';
